import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header";
import localFont from "next/font/local";

const MiSans = localFont({
  variable: '--font-mi-sans',
  preload: false,
  src: [
    {
      path: "../public/fonts/MiSansLatin-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/MiSansLatin-Semibold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/MiSansLatin-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={MiSans.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
